acl all src all

## makes our proxy anonymous too
forwarded_for delete
request_header_access From deny all
via off

http_port 3128

auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwords
auth_param basic children 5

# Should contain IP ranges belonging to cloud providers
acl blocked_networks src "/etc/squid/acl/blocked_ips.txt"
http_access deny blocked_networks

# Minimal Adblock
acl blocked_domains src "/etc/squid/acl/blocked_domains.txt"
http_access deny blocked_domains

acl authenticated proxy_auth REQUIRED

# This line will be replaced to only allow ALL clients if no username/password is given
http_access allow all

## It is best to end your rules with an explicit rule that will match any transaction.
http_access deny all
